### ISSUE TITLE
Preselect current day?

### ISSUE THREAD

**Issue by peteruithoven** [elementary/wingpanel-indicator-datetime#102]
When opening the Popover and haven't made a alternative selection, I expect it to lists the events of the current day. 
Should we preselect the current day?
Should we always select the current day on open?
@elementary/ux?

**Comment by cassidyjames** [comment]
Ah, I forgot about events on the current day. :sweat_smile: We previously removed the focus to better distinguish between today and any other selected day, but this makes a lot of sense. I'd be fine with restoring the focus on the current day when it's opened.

**Comment by cassidyjames** [comment]
See https://github.com/elementary/wingpanel-indicator-datetime/pull/77
