### ISSUE TITLE
Top status bar BUG

### ISSUE THREAD

**Issue by 420116199208022715** [elementary/wingpanel-indicator-datetime#109]
Top Time/Date Settings, Close and Display of Display Weeks Can't be Adjusted, Close and Display of Network Time Can't be Adjusted
-------------------------------------------------
The mouse and touchpad can not be set up to disable the touchpad after the external mouse is inserted.

**Comment by peteruithoven** [comment]
Please clarify. It's recommended to open 1 issue per issue. The Report problem in the System settings > About page can help you find the appropriate repository.
