### ISSUE TITLE
Opening the indicator the first time results in not responding warning

### ISSUE THREAD

**Issue by freaktechnik** [elementary/wingpanel-indicator-datetime#113]
## Steps to reproduce

- Set date formatting to de-CH (not sure if relevant)
- Click on date/time in wingpanel to open calendar popup (only occurs the first time doing this in a session)

## Expected result

Popup with calendar is shown

## Actual result

A warning that "wingpanel" isn't responding is shown. When waiting after a couple of seconds the popup appears.

**Comment by peteruithoven** [comment]
When you restart the Wingpanel (run `killall wingpanel`) you can keep reproducing this?
Does it take long to switch between months?
Can you reproduce this with the default formatting?

**Comment by freaktechnik** [comment]
I have since changed things around with my setup (like using a different GPU and keeping stuff updated) and can no longer observe this.
