### ISSUE TITLE
port to libecal-2.0

### ISSUE THREAD

**Issue by decathorpe** [elementary/wingpanel-indicator-datetime#122]
The next version of e-d-s will bump from `libecal-1.2` to `libecal-2.0` with breaking API changes.

The fedora issue for this is tracked at [RHBZ#1705553].

[RHBZ#1705553]: https://bugzilla.redhat.com/show_bug.cgi?id=1705553

**Comment by tintou** [comment]
You can follow the progress in https://github.com/elementary/wingpanel-indicator-datetime/tree/tintou/ecal-2.0

**Comment by decathorpe** [comment]
Great, thanks :)

**Comment by decathorpe** [comment]
Just checking in, is there any progress on this?

fedora 31 beta will be released soon, and this package is not installable right now.

**Comment by worldofpeace** [comment]
Also pertinent for NixOS, I won't land 3.34 without this.

**Comment by worldofpeace** [comment]
Just going to mention this again, though I know it can be annoying :smile:, @tintou any status or a branch with what you had? In NixOS I had to keep 3.32 e-d-s just for wingpanel-indicator-datetime so it could be install-able (pantheon is part of NixOS release set). While we have 6 months until the next release, others aren't as lucky.

---

> Milan Crha
> I'd like to provide some patch before the changes for eds land and rawhide is updated, but this is all vala, which is mostly out of my hands. Luckily, I've a promise from Corentin to help, though I do not know how quickly after the eds release it'll be, because he's waiting for that release (it makes sense, because eds is waiting for libical release, which should had happen on the April 30, but it did not; thus it's not sure whether the 3.33.2 will finally have these changes or not).

**Comment by quequotion** [comment]
So today I had a difficult choice to make:
Keep wingpanel-indicator-datetime, which needs old e-s-d, or install pantheon-calendar, which asks for libecal-2.0 already.

I cannot have build and install both at the same time because of their conflicting e-s-d dependencies.

Maybe I can work around by forcing pantheon-calendar to compile against an older version of e-s-d.
