### ISSUE TITLE
Enable the weekday in the panel to be hidden/shown

### ISSUE THREAD

**Issue by snwh** [elementary/wingpanel-indicator-datetime#18]
The gsettings key `org.gnome.desktop.calendar show-weekdate` exists, which can be tied to the indicator to toggle the weekday.

**Comment by danrabbit** [comment]
This key only exists if you've installed GNOME calendar :p

**Comment by snwh** [comment]
Well, let's make our own key. :P

**Comment by tintou** [comment]
@snwh By weekday, you mean "Mon, Tue, Wed…" ?
I think it might be misleading when the beginning of the week is locale-dependant.
