### ISSUE TITLE
Alignment issues

### ISSUE THREAD

**Issue by jlnr** [elementary/wingpanel-indicator-datetime#181]
I'm running the master and the days are not aligned with the week numbers or selection bubbles. I am not sure if the open PRs already address this.

![Bildschirmfoto von 2019-08-10 11-55-14](https://user-images.githubusercontent.com/70772/62820715-49c2b200-bb68-11e9-9527-d1467d044cc5.png)

This issue affects all font sizes for a change.

**Comment by jeremypw** [comment]
I think this is because space is allowed  below the number for the presence of event dots.  I agree it looks a bit strange when there are no events.  At least the week number could align with the day number.  The selection indicator is not so easy to improve - sugggestions?
