### ISSUE TITLE
wingpanel-indicator-datetime error

### ISSUE THREAD

**Issue by paulo8448** [elementary/wingpanel-indicator-datetime#198]
when we click to reveal the mini calendar it restarts the entire interface (pantheon)

![Screen-record-from-2019-11-02-04 29 48](https://user-images.githubusercontent.com/33562708/68067849-beeaf100-fd2b-11e9-81b9-d8fca5050561.gif)

this happened when i exported my outlook calendar to calendar app for now this problem

**Comment by ryonakano** [comment]
Actually, there is the same issue report (#199) posted on the day after the day you post this issue. Although yours posted a day earlier, I'll close yours in favor of #199 because that one has more detailed information like logs. But anyway, thank you for your report!
