### ISSUE TITLE
Placeholder "No Events on This Day" not being replaced by translation in Dutch

### ISSUE THREAD

**Issue by janga1** [elementary/wingpanel-indicator-datetime#204]
## Description
When I installed Elementary I set my systems language to Dutch, however, today I noticed the _No Events on This Day_ placeholder wasn't translated properly in the wingpanel's datetime-indicator.

Looking at `/po/nl.po` I can see the placeholder has been translated already and I can see nothing wrong with the code `/src/Indicator.vala:58` either. Are there others with this problem?

### Expected behavior
According to the correct translation in `/po/nl.po` the sentence should read _Geen gebeurtenissen op deze dag_, instead of _No Events on This Day_.

### Screenshots or screen recordings
![screenshot_events_wrong](https://user-images.githubusercontent.com/35235201/77774331-2858fc80-704b-11ea-9c7b-04ecd7efb1cc.png)

**Comment by ryonakano** [comment]
It looks like the Dutch translation for this string was added after the latest version of the Indicator is released. It should be shown as translated once a new version is released.

**Comment by janga1** [comment]
@ryonakano your right. My mistake.
