### ISSUE TITLE
Use Hdy.Paginator

### ISSUE THREAD

**Issue by danrabbit** [elementary/wingpanel-indicator-datetime#210]
For smooth 1:1 swiping on the calendar

**Comment by Dirli** [comment]
I don't want to trash, so I'll write here.
PR (232) not very good. Yes, it implements the required functionality, but it brings problems with it.
![screen1](https://user-images.githubusercontent.com/15650716/95398666-14058e80-090f-11eb-9d1b-640500513a99.png)
this I switched back to 2000. CalendarGrid accumulate for some reason, and if you switch for a very long time, the memory will suffer. but even worse, when you close the widget, the array of CalendarGrid is not cleared, so it all remains in memory.
![screen2](https://user-images.githubusercontent.com/15650716/95399014-e0773400-090f-11eb-90e3-8a5519a33329.png)
also, each month switch generates a lot of unnecessary actions, at each iteration, there are 4 changes to the model, which entails almost complete redrawing of everything related to events.
it seems to me that it would be more logical to leave 3 months (previous, current, next). delete dynamically everything else. the problem of memory consumption will be solved.
PS stop using the global scope and singleton, with this approach, the future is very doubtful. supporting such code is difficult. this project has much less code (compared to Music), but it is also very difficult to read.

**Comment by danrabbit** [comment]
@Dirli can you open a new issue report about this please?
