### ISSUE TITLE
Add support for tasks

### ISSUE THREAD

**Issue by marbetschar** [elementary/wingpanel-indicator-datetime#211]
Since we are building an [elementary Tasks app](https://github.com/elementary/tasks/), we should also consider showing tasks along with events in wingpanel-indicator-datetime.

**Comment by marbetschar** [comment]
does it make sense to unify [`CalendarModel`](https://github.com/elementary/calendar/blob/master/core/Model/CalendarModel.vala) and [`TaskModel`](https://github.com/elementary/tasks/blob/master/src/TaskModel.vala) and/or put them together independently from specific app integrations?

Seems like the `CalendarModel` here is a direct copy of the one in the Calendar repo - and copying the `TaskModel` in here as well feels like things are getting out of hand eventually.

Both Models do have a lot of similarities and unifying the way they work would make it easier to embed Events and Tasks throughout the system.

Maybe we can even put them into their own library (or add them to an already existing one), something like Apples [EventKit](https://developer.apple.com/documentation/eventkit).

**Comment by tintou** [comment]
I'm all for unifying them, tasks are not really far from events anyway :slightly_smiling_face: 
It really is one file so even if I agree that it's a pain to keep it synced in the 3 apps that are now using them it is just not worth creating yet another library for this :wink: if some feature is missing, it has to go to Evolution-Data-Server itself
