### ISSUE TITLE
Date & Time shows some parts English although language is not an English.

### ISSUE THREAD

**Issue by bagjunggyu** [elementary/wingpanel-indicator-datetime#23]
In case of "locale - USA, language -ko", Date & Time of wingpanel shows some part English, although other components of system shows correctly Korean.
![img_1571](https://cloud.githubusercontent.com/assets/2834031/25560107/5e4b9b2e-2d85-11e7-86e9-386df8541884.PNG)

**Comment by bagjunggyu** [comment]
And Greeters too.
![img_1574](https://cloud.githubusercontent.com/assets/2834031/25560973/7a1b8ad2-2d9c-11e7-8343-dce135b51858.JPG)

**Comment by danrabbit** [comment]
@bagjunggyu please report a separate issue against the greeter since this is a different code base :)

**Comment by bagjunggyu** [comment]
Ah :) OK
