### ISSUE TITLE
datetime indicator is too repetitive.

### ISSUE THREAD

**Issue by StevyTHOMAS** [elementary/wingpanel-indicator-datetime#24]
["copy/paste from G+"](https://plus.google.com/102440797756048578883/posts/8EecyguTYpt?cfem=1)
Hi ! I share a tiny mokup because I think the datetime wingpanel indicator is too repetitive. As you can see on the left indicator, "Samedi", "6" and "mai' were displayed 3 times and "2017" twice.﻿

![eos-date-final](https://cloud.githubusercontent.com/assets/28340969/25785472/8726c7c4-3381-11e7-9c4f-f8e62ceaa82e.png)

**Comment by quequotion** [comment]
I agree, the weekday and date labels are redundant; [so I patched them out](https://github.com/quequotion/pantheon-bzr-qq/blob/master/TESTING/wingpanel-indicator-datetime-git/no_date.patch)!
