### ISSUE TITLE
Calendar grid not visible until month changed

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/wingpanel-indicator-datetime#242]
## What Happened
Similar to https://github.com/elementary/applications-menu/issues/430 (has a nice GIF showing the issue)

After a reboot/fresh login, the calendar grid is not visible when opening the indicator

## Steps to Reproduce

1. Reboot
2. Open datetime indicator
3. See that calendar grid is not visible
4. Switch month
5. Calendar grid appears

## Platform Information

Fully up to date elementary 6.0 daily

**Comment by cassidyjames** [comment]
See: https://gitlab.gnome.org/GNOME/libhandy/-/issues/363

**Comment by danrabbit** [comment]
Should theoretically be resolved. We might just need package rebuilds

**Comment by meisenzahl** [comment]
As mentioned in https://github.com/elementary/applications-menu/issues/430 was fixed with https://gitlab.gnome.org/GNOME/libhandy/-/merge_requests/671

**Comment by meisenzahl** [comment]
Version 1.0.3 of libhandy is now available in elementary 6.0 daily and fixed this.
