### ISSUE TITLE
Add fade to left and right edges of calendar grid

### ISSUE THREAD

**Issue by hanaral** [elementary/wingpanel-indicator-datetime#243]
## Problem
Looks better than the current ridges that both sides of the calendar pages _imo_ 

## Proposal
If [this issue](https://github.com/elementary/applications-menu/issues/431) gets implemented it would be nice to have the nice scroll fade on the datetime indicator too

**Comment by danrabbit** [comment]
This would require adding underscroll nodes to Hdy.Carousel. So this feature request should be pursued there.

Closing as "Out of Scope" since this is a feature request for Hdy.Carousel and can't be fixed here
