### ISSUE TITLE
Weird shape of the circle in the calendar flyout

### ISSUE THREAD

**Issue by shahiljain** [elementary/wingpanel-indicator-datetime#247]
## What Happened
The circle that indicates the current date looks elliptical instead of a proper circle.

## Expected Behavior
I assume the shape should be a circle.

## Steps to Reproduce
Open the calendar flyout, top center.

## Platform Information
Latest Release.

![image](https://user-images.githubusercontent.com/75173792/106346772-695f1480-62df-11eb-9c8b-7c6c92c705ee.png)

**Comment by danrabbit** [comment]
Screenshot is from an older version of elementary OS. This should be fixed in the latest release
