### ISSUE TITLE
The calendar does not show the current day 

### ISSUE THREAD

**Issue by tomaswarynyca** [elementary/wingpanel-indicator-datetime#263]
As you can see in the image today is June 9th but the calendar shows that today is June 8th.
I am on the latest version of EOS 6.

![Captura de pantalla de 2021-06-09 11-13-16](https://user-images.githubusercontent.com/41587659/121371717-24459180-c914-11eb-9def-fd199761a891.png)

**Comment by queeup** [comment]
I can confirm this. If I suspend my system and wakeup next day, date stucking on suspended day.

**Comment by candiedoperation** [comment]
@cassidyjames, Just wanted to let you know about this issue.

![image](https://user-images.githubusercontent.com/47198395/129129294-4e863888-6e34-4be4-bd77-e14c737279e7.png)

Operating System: elementary OS Odin (Stable)

**Comment by cassidyjames** [comment]
1. Please try to use the issue templates provided; they ask key information to ensure a good issue report.
2. Please don't just me-to comment or @-mention people just to bump an issue; we have enough notifications as it is. :sob: Please use the built-in :+1: reaction on the original issue to mark it as affecting you.

Example of a great issue report from @wout (from the duplicate #265):

>## What Happened
>The calendar dropdown from the to bar marks the wrong day as the current day (pink bold). 10 July is the date I rebooted my computer, while we are 13 July today:
>
>![image](https://user-images.githubusercontent.com/107324/125406278-8fb9cd80-e3b0-11eb-93ce-70049f4973c8.png)
>
>## Expected Behavior
>The actual current day should be bold.
>
>## Steps to Reproduce
>1. Reboot your computer
>2. Wait a few days
>3. The day of reboot remains marked as bold
>
>## Platform Information
>![image](https://user-images.githubusercontent.com/107324/125406851-2edec500-e3b1-11eb-9b3e-00709b95325f.png)
