### ISSUE TITLE
Calender displays wrong sequence of dates in the date picker

### ISSUE THREAD

**Issue by eppixx** [elementary/wingpanel-indicator-datetime#27]
The date picker says it is tuesday (di) when it realy is monday.
Look at the Image to see what I mean.
![bildschirmfoto von 2017-05-15 21 17 30](https://cloud.githubusercontent.com/assets/1942172/26075565/06e71268-39b6-11e7-87ed-d23a0c6e9e11.png)

**Comment by eppixx** [comment]
Somehow works now as it should.
![bildschirmfoto von 2017-05-15 22 48 24](https://cloud.githubusercontent.com/assets/1942172/26078733/c4c5705e-39c0-11e7-849a-fbad7d168c6c.png)

**Comment by peteruithoven** [comment]
If it works now, could you close the issue?
