### ISSUE TITLE
Create an option for move the date/time indicator (suggestion)

### ISSUE THREAD

**Issue by roxfr** [elementary/wingpanel-indicator-datetime#276]
OS : elementary OS 6 Odin x86_64
Kernel : 5.11.0-37-generic
DE : Pantheon

Hi,
Could you create an option so that you can move the date/time indicator (see images below), please.
Thank you.
Regards,
Roxfr

PS : I did not find an option with dconf-editor.

![Neofetch](https://user-images.githubusercontent.com/52124613/135141518-ae6eabf9-8585-4ecf-aa55-6cde27b5aefd.PNG)

![wingpanel_move_datetime_indicator_to_right](https://user-images.githubusercontent.com/52124613/135134886-d534b73f-781c-45a1-9f7e-c88c27e59241.jpg)

![date time](https://user-images.githubusercontent.com/52124613/135143608-37d39254-565c-4218-a54a-29db7110989d.PNG)

![dconf-editor](https://user-images.githubusercontent.com/52124613/135142345-cae63400-7586-411a-bc7d-95c5283cf351.PNG)

**Comment by cassidyjames** [comment]
@roxfr please use the issue templates so we get the right kind of information. :smile: You can copy this into a new comment here, then fill it out:

```
<!--
* Please read and follow these tips: https://elementary.io/docs/code/reference#proposing-design-changes
* Be sure to search open and closed issues for duplicates
-->


## Problem
<!--Describe the problem that this new feature or idea is meant to address-->



## Proposal
<!--Describe the new feature or idea that you would like to propose-->



## Prior Art
<!--List any supporting examples of how others have implemented this feature-->



<!--Please be sure to preview your issue before saving. Thanks!-->
```

**Comment by roxfr** [comment]
> @roxfr please use the issue templates so we get the right kind of information. 😄 You can copy this into a new comment here, then fill it out:
> 
> ```
> 
> 
> 
> ## Problem
> 
> 
> 
> 
> ## Proposal
> 
> 
> 
> 
> ## Prior Art
> 
> 
> 
> 
> 
> ```

**Comment by cassidyjames** [comment]
@roxfr you've covered the "proposal," but I'd love to know the "problem" you're trying to solve.

**Comment by roxfr** [comment]
@cassidyjames
I would like to move the date and time to the right corner of the wingpanel.

Like this person => [https://gist.github.com/tuyendev/d07fe0d57b713995104c5740cc62d324]()

**Comment by cassidyjames** [comment]
@roxfr I understand the “what,” but I am trying to get to the “why.” It’s unlikely we would add an option like this unless we understand an actual problem it would solve.

**Comment by roxfr** [comment]
@cassidyjames
Ok I found it nice to have an option to move this indicator according to the user's preference (a simple suggestion).
Yes it is not a major problem (it is not a bug).
We can close this issue.
