### ISSUE TITLE
Changing themes causes dates and days of the week to disappear

### ISSUE THREAD

**Issue by D0J0P** [elementary/wingpanel-indicator-datetime#278]
### What Happened?

Same as #510 Where I mentioned changing themes would cause app titles in Applications to disappear.

Here, changing themes will cause days of the week, and all numbers to disappear except the current day, and past and future month's days.

### Steps to Reproduce

1. Open wingpanel-indicator-datetime and close it
2. Change theme from default to dark mode and vice versa
3. Both times, the elements mentioned will disappear. The only way to make it go back to normal is by scrolling to change the month. This will also fix #510.

### Expected Behavior

That the numbers and days of the week wouldn't disappear when changing themes.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
A common factor between this indicator and the application-menu indicator is that a Grid view inside a Hdy.Carousel.
