### ISSUE TITLE
Switching between months causes the indicator to fail to reset to today the next time it is opened 

### ISSUE THREAD

**Issue by bobby285271** [elementary/wingpanel-indicator-datetime#283]
### What Happened?

As described in title, seems to only happens on 2.3.1 (and seems that the problem is introduced in https://github.com/elementary/wingpanel-indicator-datetime/pull/280 because I cannot see this issue on 5fb0ca4534e70a902899195f3a9aa5e2d6991d56)

After switching between months then re-open the indicator, the indicator brings me to a month I never visited before and the "Go to today's date" button does not work, and after re-open the indicator again everything works again, see steps to reproduce for more info.

![屏幕截图 2021-10-30 13 40 44](https://user-images.githubusercontent.com/20080233/139521796-47a15994-69e2-4e8a-b5f0-c9fe7af264bf.png)

### Steps to Reproduce

1. Prepare a VM with fresh installed NixOS + Pantheon with `wingpanel-indicator-datetime` 2.3.1.
2. Open the indicator (it shows the calendar of October, 2021, and "30" is highlighted as expected).
3. Click the left arrow button once in the indicator (it then shows the calendar of September, 2021, and none of the date is highlighted, this is expected).
4. Close the indicator.
5. Re-open the indicator (now it shows the calendar of **November, 2021**, which is not expected, and "30" is highlighted, see above screenshot).
6. Try click the "Go to today's date" button (and **nothing happens**, which is not expected).
7. Close the indicator again.
8. Re-open the indicator (now it correctly shows the calendar of October, 2021 again).

Sorry I cannot describe this clearly in English and it is 30, October, 2021 when I found this issue.

### Expected Behavior

In step 5 mentioned above, the indicator should not show the month which I never visited before and in step 6 mentioned above, "Go to today's date" button should bring me to the calendar of October, 2021.

### OS Version

NixOS (and all Pantheon packages are the latest)

### Software Version

Latest release (2.3.1)

**Comment by jeremypw** [comment]
Yes, looks like an unintended consequence of the fix you mentioned :disappointed:
