### ISSUE TITLE
build failed on Slackware 15  "libecal-1.2" not found, tried pkgconfig and cmake

### ISSUE THREAD

**Issue by slackernetuk** [elementary/wingpanel-indicator-datetime#290]
### What Happened?

```
wingpanel-indicator-datetime-2.3.1/vapi/libical.metadata
wingpanel-indicator-datetime-2.3.1/vapi/libical.vapi
The Meson build system
Version: 0.59.4
Source dir: /tmp/snuk/wingpanel-indicator-datetime-2.3.1
Build dir: /tmp/snuk/wingpanel-indicator-datetime-2.3.1/build
Build type: native build
Project name: datetime
Project version: 2.3.1
C compiler for the host machine: ccache cc (gcc 11.2.0 "cc (GCC) 11.2.0")
C linker for the host machine: cc ld.bfd 2.37-slack15
Vala compiler for the host machine: valac (valac 0.54.3)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Program glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency wingpanel found: YES 3.0.0
Found CMake: /usr/bin/cmake (3.21.4)
WARNING: CMake Toolchain: Failed to determine CMake compilers state
Run-time dependency libecal-2.0 found: NO (tried pkgconfig and cmake)
Run-time dependency libecal-1.2 found: NO (tried pkgconfig and cmake)

../meson.build:35:4: ERROR: Dependency "libecal-1.2" not found, tried pkgconfig and cmake
```

### Steps to Reproduce

 "libecal-1.2" was not found, thats is right, but I guess libecal-1.2 isn't the problem, because libecal-2.0 is installed.

### Expected Behavior

 **pkg-config --libs libecal-2.0**

`-lecal-2.0 -lical-glib -lical -licalss -licalvcal -ledataserver-1.2 -lsecret-1 -lxml2 -lsoup-2.4 -Wl,--export-dynamic -lgmodule-2.0 -pthread -lgio-2.0 -lgobject-2.0 -lglib-2.0`

**lldd /usr/bin/evolution | grep ecal**
libecal-2.0.so.1 => /usr/lib64/libecal-2.0.so.1 (0x00007f9cba05f000)

### OS Version

Other Linux

### Software Version

Latest release (I have run all updates)

### Hardware Info

Lenovo T470 Notebook

- Intel Core i7-7500U Processor (4MB Cache, up to 3.5Ghz)
- 14" FHD (1920 x 1080) IPS, anti-glare, non-touch
- 16GB DDR4-2133MHz SODIMM (8GB+8GB)
- Intel HD Graphics 620
- 512 GB Solid State Drive, PCIe-NVMe OPAL2.0

System
Slackware 15 / GCC 11.2.0 / Kernel 5.15.4
CMake Version: 3.21.4
Meson Version: 0.59.4

**Comment by tintou** [comment]
It will first try to use `libecal-2.0` if it is installed but it seems that the development files are not installed on your system.

**Comment by tintou** [comment]
We can't reproduce the issue on elementary OS, you have to figure-out why your pkg-config used in meson isn't finding your `libecal-2.0` library

**Comment by slackernetuk** [comment]
The Slackware Packagem-Management doesn't split the header files. I could solve the problem, evolution-data-server just needed a rebuild.  thanks
