### ISSUE TITLE
"Formats" from the Language&Region settings fixes first day of the week, but doesn't affect the date format.

### ISSUE THREAD

**Issue by michallepicki** [elementary/wingpanel-indicator-datetime#34]
My system is set to: Language = English, Region = United States, Formats = Poland

Formats on the settings page suggests that the date should be: "weekday, DD mon YEAR" but instead on the wingpanel I see "pon, cze 26".

 The format is wrong, it should be "pon, 26 cze"

**Comment by piotrdrag** [comment]
We’ve fixed the first issue a while ago: https://l10n.elementary.io/projects/wingpanel/wingpanel-indicator-datetime/pl/#history — but it’s still not in git for some reason.
