### ISSUE TITLE
Week Numbers not styled properly

### ISSUE THREAD

**Issue by ayoisaiah** [elementary/wingpanel-indicator-datetime#35]
When "Show Date & Time" is toggled On in the Date & Time settings, it appears to me that the styling is a little off (lack of padding e.t.c).

This is on Elementary 0.4.1 Loki

![screenshot from 2017-06-28 20 49 49](https://user-images.githubusercontent.com/13372163/27657182-aefc3ba4-5c43-11e7-932d-6e81d569c0ca.jpg)

**Comment by danrabbit** [comment]
This was resolved in #22
