### ISSUE TITLE
Calendar scrolling lag

### ISSUE THREAD

**Issue by caudatecoder** [elementary/wingpanel-indicator-datetime#38]
Months scrolling lags heavily after last update.
Moreover seems like the whole wingpanel freezes. I'm using `System Load Indicator` and it's stops for a while on calendar scroll.

I've got a PC that powerful enough:
- Quad-Core Intel® Core™ i5-3570K CPU @ 3.40GHz
- 12.0 GB memory

And it wasn't like this before update.
So it seems like a bug.

**Comment by RonnyDo** [comment]
Can confirm that. When going fore and back with the arrow buttons the calender always hangs like about one second.

**Comment by peteruithoven** [comment]
Taking some measurements it looks like the `for` loop of `Grid.set_range` is taking up a lot of time:
https://github.com/elementary/wingpanel-indicator-datetime/blob/master/src/Widgets/calendar/Grid.vala#L99-L126

**Comment by jlnr** [comment]
I'm not sure if this is the same issue, but the scrolling is fast for me when I restart wingpanel, and then gets slower over time. Just opening the panel and scrolling up and down on the mouse wheel for a bit increases the delay to around a second, on an i7 desktop.

**Comment by jeremypw** [comment]
Scrolling does not seem to lag now, but, using touchpad scroll at least, is not consistent.  The scroll action sometimes changes a month (or more) and sometimes not.  Seems to depend on speed of movement.

**Comment by jeremypw** [comment]
@tintou commented on #172:
>I'd prefer to wait until we get proper gesture support in the Gtk stack with GtkGesture (something like https://valadoc.org/gtk+-3.0/Gtk.GestureSwipe.html )

**Comment by danrabbit** [comment]
calendar should be consistently more performant now
