### ISSUE TITLE
current master (ab6db27) fails to build due to CMake error (?)

### ISSUE THREAD

**Issue by decathorpe** [elementary/wingpanel-indicator-datetime#43]
During compilation, I get the following cryptic error (full absolute paths to build directory shortened to "..." for easier reading):

```
cd .../src && /usr/bin/valac -C -b .../src -d .../src --pkg=wingpanel-2.0 --pkg=glib-2.0>=2.32 --pkg=granite --pkg=libecalendar-1.2 --pkg=libedataserver-1.2 --pkg=libical --pkg=libsoup-2.4 --target-glib=2.32 --vapidir=.../vapi --thread -g --save-temps .../src/Indicator.vala .../src/Widgets/PanelLabel.vala .../src/Widgets/calendar/Calendar.vala .../src/Widgets/calendar/CalendarModel.vala .../src/Widgets/calendar/CalendarView.vala .../src/Widgets/calendar/ControlHeader.vala .../src/Widgets/calendar/Util.vala .../src/Widgets/calendar/Grid.vala .../src/Widgets/calendar/GridDay.vala .../src/Widgets/calendar/Header.vala .../src/Widgets/calendar/WeekLabels.vala .../src/Services/TimeManager.vala .../src/Services/ClockSettings.vala .../src/Services/SettingsManager.vala .../src/config.vala .../src/.../vapi/posix-extension.vapi
warning: --save-temps has no effect when -C or --ccode is set
error: .../src/.../vapi/posix-extension.vapi not found
make[2]: *** [src/CMakeFiles/datetime.dir/build.make:125: src/datetime_valac.stamp] Error 1
```

It looks like the path to the "posix-extension.vapi" file contains the build directory path ("...") *twice*, which results in vala not being able to find the file.

**Comment by jeremypw** [comment]
Master builds correctly for me using the command (assuming no existing build directory):

```
mkdir ./build && cd ./build && cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE="Release" .. && make
```

Where does the command starting ```cd .../src && /usr/bin/valac -C -b .../src -d .../src --pkg=wingpanel-2.0 --pkg=glib-2.0>=2.32 --pkg=granite .........```

quoted in the initial report come from?

**Comment by decathorpe** [comment]
Here's a full build log. The commands are the same as for you, except for some more CMake flags that are set on fedora by default.

https://gist.github.com/decathorpe/d96a3812b3db73f8ce0ba817b5d8f8ea#file-wp-ind-datetime-build-log-txt-L98

**Comment by jeremypw** [comment]
There is a ".." missing from the cmake command - your command works if this is added.  (I haven't checked whether an in tree build works - maybe not.)   If you need to do an in tree build, does tintou's linked PR fix the problem?

**Comment by decathorpe** [comment]
You're right, I've not switched this package to out-of-tree builds yet - because both in-tree and out-of-tree builds have been failing with this same error for months:

Log of out-of-tree build, with the same error occurring:
https://gist.github.com/decathorpe/e1f9893d573bd438b9393f031bd7e00e

**Comment by jeremypw** [comment]
Looks like ${CMAKE_SOURCE_DIR} is being expanded to the incorrect path but the reason is not clear to me, especially as it is used in the root CMakeLists.txt without error; but tbh I am not sufficiently expert with cmake to interpret all your extra flags. You could try setting this this explicitly in the command I suppose otherwise hopefully https://github.com/elementary/wingpanel-indicator-datetime/pull/49 will fix it for you as it avoid using that variable at that point ( I cannot check as I have not reproduced the error).

**Comment by jeremypw** [comment]
@decathorpe:  Did you try tintou's fix?  PR#49

**Comment by decathorpe** [comment]
Yes, #49 fixes the problem in manual testing.

**Comment by jeremypw** [comment]
OK, in that case I'll approve it - thanks.
