### ISSUE TITLE
Wingpanel time ignores Date & Time settings when Region is set to a 24 hour format region

### ISSUE THREAD

**Issue by aljelly** [elementary/wingpanel-indicator-datetime#47]
### Summary
I live in the UK and I set the system region and formats to United Kingdom (under English in the Language & Region settings). United Kingdom is defined as a 24 hour format but I'm used to AM/PM.

It seems that if you set Region (not Formats) in Language & Region to one that uses a 24 hour time format, for example United Kingdom or Australia under English or France under français, the time shown in Wingpanel changes to 24 hour format after logging in again, regardless of the time format set in Date & Time. It won't let me change it to AM/PM.

However, if you have the system set to a region that uses AM/PM (e.g. United States), you can freely change between AM/PM and 24h formats in the Date & Time settings.

_Update: Upon further testing, time pickers seem to be partially affected by this as well. The input shows 24 hour time, but when the clock is clicked, it shows a AM/PM picker if the time format in Date & Time is set to AM/PM._

(I've also noticed that Pantheon's greeter seems to act strange with time formats, but that's a different issue and it's already been reported.)

### Steps to reproduce
1. Go to Language & Region in System Settings and set the Region to United Kingdom under English (or any other region that has 24 hour format by default, for example this bug also applies to France under "français").
2. Log out and in again
3. The time in Wingpanel appears in 24 hour format, regardless of what the time format is set to in Date & Time.
4. Go to Date & Time in System Settings and try to change the time format. It won't change.

### What is expected
Wingpanel time format only reflects the time format set in Date & Time, even when the region is changed.

### What actually happens
Wingpanel time format is overridden by Region being set to a 24 hour format region and can't be changed in that state.

**Comment by jlnr** [comment]
I can't reproduce this with the current Juno daily build. Wingpanel respects this setting even without logging out and in again.

**Comment by giovannicaligaris** [comment]
I am having the same issue. I tried just about everything and I can't find a solution.

**Comment by giovannicaligaris** [comment]
@BaptisteGelez Yes. As @aljelly mentioned, if I switch to my region to US the problem goes away.

**Comment by aljelly** [comment]
This is still an issue as of Juno stable.

**Comment by aljelly** [comment]
I've found the problem. It's because of Granite's translation files, not this module.
