### ISSUE TITLE
wingpanel-indicator-datetime looks deformed with fonts greater than 10pt

### ISSUE THREAD

**Issue by worldofpeace** [elementary/wingpanel-indicator-datetime#50]
#### Here's some screenshots so you can understand me.

With fonts of 10pt. Looks nice.
![wingpanel_default_font](https://user-images.githubusercontent.com/28888242/31857261-96d859e0-b6a7-11e7-91cd-a2c46eec40fe.png)

Here's it with 12pt. Starting to look squished. 
![wingpanel_bigger_font](https://user-images.githubusercontent.com/28888242/31857277-3eea6ed4-b6a8-11e7-874a-5e30b2f53f57.png)

Now here's with fonts really big.
![wingpanel_biggest_font](https://user-images.githubusercontent.com/28888242/31857298-13c80346-b6a9-11e7-89fe-84902afbfced.png)

Any idea's an how to combat this?
I would imagine that we would want this indicator to look it's best even when fonts are really big.

**Comment by worldofpeace** [comment]
@fabianthoma 
It's been a while since I opened this so I might see If I can still reproduce it.

I think the ovalness happens when you change the scalling factor if I recall.

**Comment by worldofpeace** [comment]
I can reproduce the ovalness( I guess that's what I'm calling it) if you change the text scaling factor.

As for the horizontal spacing trip, it pretty much happens whenever you change the size of the fonts larger than 10pt.

**Comment by jlnr** [comment]
I've set the font to "larger" using System Settings, and my bubbles are vertical ellipses. No scaling factor, but I'm on a de_DE system where weekdays are abbreviated as two letters, not three, which probably compresses the grid.

**Comment by danrabbit** [comment]
This appears to be resolved with fonts set to "Larger" in git master:

![Screenshot from 2019-07-17 10 51 18@2x](https://user-images.githubusercontent.com/7277719/61398462-ec955280-a880-11e9-8571-d4b78ba877b1.png)

**Comment by worldofpeace** [comment]
Was that verified on Low DPI displays @danrabbit?

That's only where the issue with the bubbles becoming vertical ellipses can properly be observed.

**Comment by jlnr** [comment]
I'm on a LoDPI, the bubbles look reasonably circular with "Larger" fonts, but still like an ellipse with "Largest" fonts.

**Comment by worldofpeace** [comment]
https://github.com/elementary/wingpanel-indicator-datetime/pull/184 fixed this

**Comment by jlnr** [comment]
@worldofpeace The bubbles are still elliptic for me with the Large and Largest text sizes (just built from master).

**Comment by worldofpeace** [comment]
I think perhaps it was improved but maybe not resolved. I'll keep this one closed, but as reference in #161. The appearances and condition to make those have changed a lot, so it's more of a WIP bug fix.

**Comment by J0Ar** [comment]
Still an issue in the latest release 2.2.0 of wingpanel-indicator-datetime 
Here for example font size 10 with scaling factor 1.3 … 

![Bildschirmfoto von 2019-11-01 15-56-10](https://user-images.githubusercontent.com/23266409/68033594-4d298d80-fcc0-11e9-898a-6f3c3287a991.png)

Otherwise, this release is a great visual improvement for the event indication! Thank you :)

**Comment by worldofpeace** [comment]
@J0Ar Its been confirmed in https://github.com/elementary/wingpanel-indicator-datetime/issues/161, I believe we'll continue to track the issue there as the report has images that are up to date.
