### ISSUE TITLE
Long event names break style

### ISSUE THREAD

**Issue by Thalexander** [elementary/wingpanel-indicator-datetime#51]
Some long event names break the style of the indicator making the settings button seem to go past the end of the popup
![screenshot from 2017-11-22 22 43 17](https://user-images.githubusercontent.com/18336287/33152819-9e08c5a4-cfd6-11e7-9b66-21090b6675f1.png)

Also really long words do not fall back to char wrapping which creates a weird appearance
![screenshot from 2017-11-22 22 43 36](https://user-images.githubusercontent.com/18336287/33152838-b569cdc4-cfd6-11e7-973b-93e6590b9bd5.png)

**Comment by worldofpeace** [comment]
Uh muh gawd. Just weird.
