### ISSUE TITLE
ISO 8601 for date/time format

### ISSUE THREAD

**Issue by MathyM** [elementary/wingpanel-indicator-datetime#57]
There used to be a `custom-time-format` available option in `com.canonical.indicator.datetime`, but this options seems to be gone

The only option I have is to switch between 12h and 24h clocks. I'm stuck with a date format that is alien to me (weekday, 3-letter month, day), when I'd much prefer to see dates in ISO 8601 format (yyyy-mm-dd hh:mm). This shouldn't be determined by my region (which uses days before months, so the current format is wrong anyway), but by some setting specific for dates.

**Comment by errata9** [comment]
Seems to be hardcoded in src/Widgets/PanelLable.vala:

private void update_labels () {
        /// TRANSLATORS: Date format in the panel following http://valadoc.org/#!api=glib-2.0/GLib.DateTime.format */
date_label.set_label (Services.TimeManager.get_default ().format (_("%a, %b %e")));
