### ISSUE TITLE
Event showing up on incorrect days

### ISSUE THREAD

**Issue by peteruithoven** [elementary/wingpanel-indicator-datetime#59]
I have a (repeated) event that's showing up on days it shouldn't. 
It's an event that should appear every first Saturday of every month, at 13:00 - 17:00. 

Some notes:
- For some reason it appears on 3 - 31 mrt and 2 - 30 june. (It starts after the first Saturday)
- Beside that Saturday it doesn't specify a time, as if it's a whole day event. 
- I have other (monthly) repeating events that are only shown on the appropriate days. 
- The event appears on the appropriate days in the Calendar app. 
- All events on the first Saturday on every month seems to create this issue. 
- Creating monthly repeating events on the first Friday or Sunday don't create this issue.

`ical.as_ical_string` of shown event:
``` ical
BEGIN:VEVENT
UID:20180105T141524Z-6660-1000-1-0@xps
DTSTAMP:20180105T141524Z
SUMMARY:RC Leidsche Rijn
DTSTART;TZID=/freeassociation.sourceforge.net/Europe/Amsterdam:
 20180106T130024
DTEND;TZID=/freeassociation.sourceforge.net/Europe/Amsterdam:
 20180106T170024
LOCATION:Vrijetijdscentrum Voorn\, Akkrumerraklaan 131 utrecht
CREATED:20180105T141635Z
LAST-MODIFIED:20180306T193607Z
RRULE:FREQ=MONTHLY;BYDAY=1SA
X-EVOLUTION-CALDAV-HREF:
 /remote.php/dav/calendars/peteruithoven/extern/20180105T141524Z-6660-1000-
 1-0_xps-20180105T141635Z.ics
X-EVOLUTION-CALDAV-ETAG:"5a9e585da4c2a3a43673714fd1328d54"
END:VEVENT
```

I see the same ical string when I click on the Saterday it should show up. 

`Util.event_date_ranges` gives a weird list of date ranges on the event: 
- 2018-01-06T00:00:00+0100 - 2018-01-06T00:00:00+0100
- 2018-02-03T00:00:00+0100 - 2018-02-03T00:00:00+0100
- 2018-03-03T00:00:00+0100 - 2018-03-03T00:00:00+0100
- 2018-03-03T00:00:00+0100 - 2018-04-03T00:00:00+0200

The last date range suddenly covers a whole month, where the end date has another UTC time offset?

**Comment by peteruithoven** [comment]
If I interpret the code correctly `Utils.get_date_from_ical_day` should return the date specified by the day part of the RRule of the event (`1SA` for example) within the month of the given date. 
In my case it gets: 
- date: `2018-04-06T00:00:00+0200`
- day: `1SA` (translated to `15`)
But for some reason this results in `2018-03-31T00:00:00+0200`, which is a Saturday, but the wrong Saturday.

**Comment by danrabbit** [comment]
There is a PR here for Calendar regarding ical timezones. It seems like that is close to being approved, so we'll probably want to adapt those fixes here as well: https://github.com/elementary/calendar/pull/515

**Comment by marbetschar** [comment]
Ran into this timezone issue too (see below) - and it is fixed in Calendar. So adapting `timezone_from_ical` in Wingpanel is definetely a good idea. Will do this as soon as I have some spare time.

Note: the times shown in Calendar are correct - the ones in Wingpanel are wrong:

![Screenshot from 2020-09-28 21-03-53](https://user-images.githubusercontent.com/392542/94474979-bcf51080-01ce-11eb-9c2d-da7bc5eb56e3.png)
