### ISSUE TITLE
Build failure: `Posix' already contains a definition for `NLTime'

### ISSUE THREAD

**Issue by quequotion** [elementary/wingpanel-indicator-datetime#61]
Lately I've been unable to build wingpanel-indicator-datetime with this error.
I have vala 0.40.3-1 installed in Archlinux; it comes with a posix.vapi that contains a very similar definition for NLTime.

https://github.com/elementary/wingpanel-indicator-datetime/blob/60fedbc5503269e01a478af32ad6e41dc8a7554d/vapi/posix-extension.vapi#L4

**Comment by tintou** [comment]
Indeed, our Posix additions were merged upstream
