### ISSUE TITLE
Wrong translation of month names is shown in ControlHeader in Juno

### ISSUE THREAD

**Issue by jendamarek** [elementary/wingpanel-indicator-datetime#74]
Due to an update of GLib (to 2.56 in Juno) the time format in ControlHeader.vala produces wrong month names in Czech (and maybe other languages as well). The time format that needs to be used is %OB instead of %B. (its for standalone months without a day number). See https://valadoc.org/glib-2.0/GLib.DateTime.format.html
I haven't tested if this format is backwards compatible. The same bug occures through many elementary apps (I tryed to report all the occurrences).

**Comment by jendamarek** [comment]
Yes, I know. I translated that. The change affects many Slavic languages (according to that documentation link) and doesn't affect the other ones, so It would probably be better to have it in the original string, but the translation solution may also work.

**Comment by tintou** [comment]
Would you mind providing a merge request for any place that you spotted this issue :)
From the documentation:
>Additionally, when O is used with B, b, or h, it produces the alternative form of a month name. The alternative form should be used when the month name is used without a day number (e.g., standalone). It is required in some languages (Baltic, Slavic, Greek, and more) due to their grammatical rules. For other languages there is no difference. %OB is a GNU and BSD strftime() extension expected to be added to the future POSIX specification, %Ob and %Oh are GNU strftime() extensions.
So it seems that It has to be in the source string. Thanks for making us aware of this issue.

**Comment by jendamarek** [comment]
Yes, no problem :)
