### ISSUE TITLE
Events in the popup calendar should appear as dots

### ISSUE THREAD

**Issue by lainsce** [elementary/wingpanel-indicator-datetime#91]
As it stands, the current behavior for showing upcoming events in the month:
![screenshot from 2018-08-20 13-19-43](https://user-images.githubusercontent.com/4886639/44353156-96573e00-a47c-11e8-8751-006a055b1cfa.png)

I propose then, that days with events should have a dot, maybe red-colored, or not, up to 4 dots:
![screenshot from 2018-08-18 08 03 42 1](https://user-images.githubusercontent.com/4886639/44353189-b129b280-a47c-11e8-83af-80f0ca650f89.png)

**Comment by peteruithoven** [comment]
I love this idea. 
It might be interesting to use the color configured for the Calendar of that event. That way users who have split up events into work and social can distinguish those in a quick glance. The only downside would be that some colors might be hard to see. 

Related to: https://github.com/elementary/wingpanel-indicator-datetime/issues/13

**Comment by peteruithoven** [comment]
You're approach in https://github.com/elementary/files/pull/973 seems relevant for this feature.

**Comment by lainsce** [comment]
I dunno if it'd help, since it'd require rows between weeks to be there.

**Comment by peteruithoven** [comment]
@lainsce's great mockup that also contains these event dots:
![datetime-popover-redesign+events-pane](https://user-images.githubusercontent.com/523210/60595180-c5318680-9da6-11e9-8390-713859a12f22.png)
Mockup PR: https://github.com/elementary/mockups/pull/10
