### ISSUE TITLE
"Month and year button" includes day of the month

### ISSUE THREAD

**Issue by jlnr** [elementary/wingpanel-indicator-datetime#94]
It should say "September 2018", not "1. September 2018":

![screenshot von 2018-09-06 13 57 04](https://user-images.githubusercontent.com/70772/45156050-46e37280-b1dd-11e8-8b3c-d0f79b0a4bbc.png)

This is with a German locale, if that makes a difference.

**Comment by tintou** [comment]
It is indeed an issue with the German locale
https://weblate.elementary.io/translate/wingpanel/wingpanel-indicator-datetime/de/?checksum=179f0074711465bf

**Comment by danrabbit** [comment]
Closing as "Out of Scope" because this has to be solved in Weblate
